site_name: Apuntes Programación 1º DAM
site_url: https://RomanOlea.github.io/apuntes-programacion

theme:
  name: material
  language: es
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.copy
    - search.highlight

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Hasiera: index.md
  - Programazioa:
    - Gaia 1 — Programazio Oinarriak:
      - Gaia 1.0 — Programazio Oinarriak:
        - 1.0.0 Programazio Oinarriak: programazioa/gaia1/programazio-oinarriak.md
        - 1.0.1 Aurkezpena: programazioa/gaia1/aurkezpena.md

