site_name: Apuntes Programación 1º DAM
site_url: https://RomanOlea.github.io/apuntes-programacion

theme:
  name: material
  language: es
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.copy
    - search.highlight

markdown_extensions:
 - toc:
      toc_depth: 0
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Hasiera: index.md
  - Programazioa:
    - Gaia 1 — Programazio Oinarriak:
      - 1.1 — Programazio Oinarriak: programazioa/gaia1/programazio-oinarriak.md
      - 1.2 — Java Programazio Lengoaia: programazioa/gaia1/java-programazio-lengoaia.md      
      - 1.3 — Datuak, aldagaiak eta eragileak: programazioa/gaia1/datuak-aldagaiak-eragileak.md            
      - 1.4 — GEHIGARRI - Java Scanner: programazioa/gaia1/java-scanner.md            
      - 1.5 — GEHIGARRI - Mota bihurketa: programazioa/gaia1/mota-bihurketa.md            
      - 1.6 — GEHIGARRI - Konstanteak: programazioa/gaia1/konstanteak.md                  

